// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: books.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, created_at, updated_at, title, description, image_link, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, title, description, image_link, user_id
`

type CreateBookParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	ImageLink   string
	UserID      uuid.UUID
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.ImageLink,
		arg.UserID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ImageLink,
		&i.UserID,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books 
WHERE id = $1 AND user_id = $2
`

type DeleteBookParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBook(ctx context.Context, arg DeleteBookParams) error {
	_, err := q.db.ExecContext(ctx, deleteBook, arg.ID, arg.UserID)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT id, created_at, updated_at, title, description, image_link, user_id FROM books 
ORDER BY created_at DESC
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.ImageLink,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByUserAndID = `-- name: GetBookByUserAndID :one
SELECT id, created_at, updated_at, title, description, image_link, user_id FROM books
WHERE id = $1 AND user_id = $2
`

type GetBookByUserAndIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBookByUserAndID(ctx context.Context, arg GetBookByUserAndIDParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByUserAndID, arg.ID, arg.UserID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ImageLink,
		&i.UserID,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books 
SET updated_at = $1, title = $2, description = $3
WHERE id = $4 AND user_id = $5
`

type UpdateBookParams struct {
	UpdatedAt   time.Time
	Title       string
	Description string
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}
